name: 'TuyenPKT Host File (Beta)'
description: 'Generate provenance attestations for build artifacts'
author: 'TuyenPKT'


jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: ./makefile.sh


