name: TuyenPKt

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:



jobs:
  test:
    name: Test on node
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
    - name: Checkout
      uses: actions/checkout@v4.1.5
    - name: Make the script files executable
      run: chmod +x ./host.sh
    - name: javascript
      run: ./host.sh


