name: MakeFiles

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write

    steps:
      - name: Cat for GitHub Actions
        uses: pCYSl5EDgo/cat@1.0.1 
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x ./makefile.sh
      - name: Get version
        id: vars
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - name: Run linter
        run: ./makefile.sh
