name: MakeFiles

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      issues: write
      pull-requests: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x ./makefile.sh
      - name: Run linter
        run: ./makefile.sh
