name: MakeFiles

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x ./makefile.sh
      - name: Run linter
        run: ./makefile.sh
